version: '3'
services:
  redis:
    container_name: some-redis
    image: redis:4.0.13 
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      
  mysql:
   container_name: some-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: hellokoding
    MYSQL_ROOT_HOST: '%'
   command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
   ports:
   - "3306:3306"
   restart: always
   
  mongodb:
    container_name: some-mongo
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    restart: always
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    
  neo4j:
    container_name: some-neo4j
    image: neo4j:3.0
    volumes:
      - ./plugins:/plugins
      - ./neo4j/data:/data
      - ./import:/import
      - ./db/dbms:/data/dbms
    #restart: always #内存不足，总是失败
    ports:
      - 7474:7474
      - 7687:7687

